spring:
  application:
    name: bookyard

  datasource:
    url: jdbc:postgresql://postgres:5432/bookyard
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: VIESj/LtxJ05wroQ1H+Z6iqc3FRVsTpxeR8SKu1rc4Y=
  # expiration: 86400000
  expiration: 180000